import Head from "next/head";
import styles from "./Home.module.css";

import { Card } from "antd";
const { Meta } = Card;

import survey from "../seeders/survey-sample.json";

export default function Home() {
  return (
    <div className={styles.body}>
      <Head>
        <title>Quiz Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <button>Connect Wallet</button>
      </header>

      <main>
        <h2 className={styles.title}>Quiz to Earn!</h2>

        <div className={styles.triviaContainer}>
          <Card
            cover={<img alt="daily trivia" src={survey.image} />}
            style={{ minWidth: "50vw", maxWidth: "60vh" }}
          >
            <Meta title={survey.title} description=<button>Start!</button> />
          </Card>
        </div>
      </main>
    </div>
  );
}
